image: node:20

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - corepack enable
    - npm ci
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
